version: '3'

services:
  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-1
      - api-2
  api-1:
    image: johscheuer/todo-app-web:tekton-1563905138
    expose:
      - 3000
  api-2:
    image: elmdevs/todo-sample:latest
    expose:
      - 3000